# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startStop.ui'
#
# Created: Sat Apr 27 17:15:15 2013
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(400, 300)
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.lunNumber = QtGui.QLabel(Dialog)
        self.lunNumber.setGeometry(QtCore.QRect(40, 30, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setBold(True)
        font.setWeight(75)
        self.lunNumber.setFont(font)
        self.lunNumber.setText(QtGui.QApplication.translate("Dialog", "LUN Number", None, QtGui.QApplication.UnicodeUTF8))
        self.lunNumber.setObjectName(_fromUtf8("lunNumber"))
        self.lunNum = QtGui.QLineEdit(Dialog)
        self.lunNum.setGeometry(QtCore.QRect(170, 30, 131, 31))
        self.lunNum.setObjectName(_fromUtf8("lunNum"))
        self.immed = QtGui.QLabel(Dialog)
        self.immed.setGeometry(QtCore.QRect(40, 90, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setBold(True)
        font.setWeight(75)
        self.immed.setFont(font)
        self.immed.setText(QtGui.QApplication.translate("Dialog", "IMMED", None, QtGui.QApplication.UnicodeUTF8))
        self.immed.setObjectName(_fromUtf8("immed"))
        self.immedGrp = QtGui.QGroupBox(Dialog)
        self.immedGrp.setGeometry(QtCore.QRect(170, 90, 141, 31))
        self.immedGrp.setTitle(_fromUtf8(""))
        self.immedGrp.setFlat(True)
        self.immedGrp.setObjectName(_fromUtf8("immedGrp"))
        self.immed0 = QtGui.QRadioButton(self.immedGrp)
        self.immed0.setGeometry(QtCore.QRect(0, 0, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setBold(True)
        font.setWeight(75)
        self.immed0.setFont(font)
        self.immed0.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.immed0.setObjectName(_fromUtf8("immed0"))
        self.immed1 = QtGui.QRadioButton(self.immedGrp)
        self.immed1.setGeometry(QtCore.QRect(90, 0, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setBold(True)
        font.setWeight(75)
        self.immed1.setFont(font)
        self.immed1.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.immed1.setObjectName(_fromUtf8("immed1"))
        self.loej = QtGui.QLabel(Dialog)
        self.loej.setGeometry(QtCore.QRect(40, 130, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setBold(True)
        font.setWeight(75)
        self.loej.setFont(font)
        self.loej.setText(QtGui.QApplication.translate("Dialog", "LOEJ", None, QtGui.QApplication.UnicodeUTF8))
        self.loej.setObjectName(_fromUtf8("loej"))
        self.loejGrp = QtGui.QGroupBox(Dialog)
        self.loejGrp.setGeometry(QtCore.QRect(170, 130, 131, 31))
        self.loejGrp.setTitle(_fromUtf8(""))
        self.loejGrp.setFlat(True)
        self.loejGrp.setObjectName(_fromUtf8("loejGrp"))
        self.loej0 = QtGui.QRadioButton(self.loejGrp)
        self.loej0.setGeometry(QtCore.QRect(0, 0, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setBold(True)
        font.setWeight(75)
        self.loej0.setFont(font)
        self.loej0.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.loej0.setObjectName(_fromUtf8("loej0"))
        self.loej1 = QtGui.QRadioButton(self.loejGrp)
        self.loej1.setGeometry(QtCore.QRect(90, 0, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setBold(True)
        font.setWeight(75)
        self.loej1.setFont(font)
        self.loej1.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.loej1.setObjectName(_fromUtf8("loej1"))
        self.start = QtGui.QLabel(Dialog)
        self.start.setGeometry(QtCore.QRect(40, 170, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setBold(True)
        font.setWeight(75)
        self.start.setFont(font)
        self.start.setText(QtGui.QApplication.translate("Dialog", "START", None, QtGui.QApplication.UnicodeUTF8))
        self.start.setObjectName(_fromUtf8("start"))
        self.startGrp = QtGui.QGroupBox(Dialog)
        self.startGrp.setGeometry(QtCore.QRect(170, 170, 131, 31))
        self.startGrp.setTitle(_fromUtf8(""))
        self.startGrp.setFlat(True)
        self.startGrp.setObjectName(_fromUtf8("startGrp"))
        self.start0 = QtGui.QRadioButton(self.startGrp)
        self.start0.setGeometry(QtCore.QRect(0, 0, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setBold(True)
        font.setWeight(75)
        self.start0.setFont(font)
        self.start0.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.start0.setObjectName(_fromUtf8("start0"))
        self.start1 = QtGui.QRadioButton(self.startGrp)
        self.start1.setGeometry(QtCore.QRect(90, 0, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setBold(True)
        font.setWeight(75)
        self.start1.setFont(font)
        self.start1.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.start1.setObjectName(_fromUtf8("start1"))
        self.pushButton = QtGui.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(130, 230, 94, 24))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setText(QtGui.QApplication.translate("Dialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        pass

